### **차원 - 미니퀘스트**

1번 퀘스트



In [5]:
import numpy as np
array = np.array([[1,2], [3,4],[5,6],[7,8]])

In [6]:
print(array.ndim)

2


2번 미니퀘스트

In [7]:
array = np.array([10, 20, 30, 40, 50, 60])
new_matrix = array.reshape(2, 3)
print(new_matrix)

[[10 20 30]
 [40 50 60]]


3번 미니퀘스트

In [8]:
import numpy as np
array = np.array([7, 14, 21])
new_array = array[np.newaxis,:]
print(new_array)
print(new_array.shape)
print(new_array.ndim)

[[ 7 14 21]]
(1, 3)
2


### **Shape - 미니퀘스트**

1번 퀘스트

In [9]:
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array.shape)

(2, 3)


2번 퀘스트

In [10]:
array = np.array([10, 20, 30, 40, 50, 60])
new_array = array.reshape(2,3)
print(new_array)

[[10 20 30]
 [40 50 60]]


3번 퀘스트

In [11]:
import numpy as np
array = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
])

new_array = array.reshape(3,2,2)
print(new_array)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


### **데이터 타입 - 미니퀘스트**

1번 퀘스트

In [12]:
import numpy as np
array = np.array([10, 20, 30])
print(array.dtype)

int64


2번 퀘스트

In [13]:
array = np.array([1,2,3])
converted_array = array.astype(np.float64)
print(converted_array.dtype)

float64


3번 퀘스트

In [14]:
array = np.array([100,200,300])
converted_array = array.astype(np.uint8)
print(converted_array.nbytes)

3


### **인덱싱 - 미니퀘스트**

1번 퀘스트

In [15]:
import numpy as np
array = np.array([10, 20, 30, 40, 50])
print(array[0], array[-1])

10 50


2번 퀘스트

👉 주어진 2차원 배열에서 첫 번째 열과 두 번째 행을 출력하는 코드를 작성하세요.

In [16]:
import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(matrix[:,0])
print(matrix[0,])

[1 4 7]
[1 2 3]


3번 퀘스트

👉 주어진 배열에서 10보다 큰 요소들만 선택하고, 해당 요소들의 인덱스를 출력하는 코드를 작성하세요.

In [17]:
import numpy as np
array = np.array([5, 15, 8, 20, 3, 12])
filtered = array[array>10]
indices = np.where(filtered)
print(indices[0])

[0 1 2]


### **연산 - 미니퀘스트**

1번 퀘스트

<aside>
👉 주어진 NumPy 배열에서 요소별(Element-wise) 덧셈을 수행하는 코드를 작성하세요.

</aside>

In [18]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a+b)

[5 7 9]


2번 퀘스트

<aside>
👉 다음 NumPy 배열에서 브로드캐스팅을 활용하여 각 행에 `[1, 2, 3]`을 더하는 코드를 작성하세요.

</aside>

In [19]:
import numpy as np
matrix = np.array([[10, 20, 30], [40, 50, 60]])
vector = np.array([1, 2, 3])
print(matrix+vector)

[[11 22 33]
 [41 52 63]]


3번 퀘스트

<aside>
👉 주어진 2차원 NumPy 배열에 대해, 축(axis)을 기준으로 최댓값을 구하고 최종 배열의 차원을 출력하는 코드를 작성하세요.

</aside>

In [20]:
import numpy as np
array = np.array([[3, 7, 2], [8, 4, 6]])
array_max1 = np.max(array, axis=0)
array_max2 = np.max(array, axis=1)
print(array_max1, array_max1.ndim)
print(array_max2, array_max2.ndim)

[8 7 6] 1
[7 8] 1


### **유니버설 함수 - 미니퀘스트**

1번 퀘스트

<aside>
👉 배열 `[1, 2, 3, 4]`에 대해 NumPy의 유니버설 함수를 사용하여 모든 요소를 제곱한 결과를 출력하는 코드를 작성하세요.

</aside>

In [21]:
array = np.array([1,2,3,4])
print(np.power(array,2))

[ 1  4  9 16]


2번 퀘스트

<aside>
👉 다음 두 배열의 요소별 합을 계산하고, 결과를 새로운 배열이 아닌 기존 배열에 저장하는 코드를 작성하세요.

</aside>

In [22]:
array1 = np.array([10, 20, 30])
array2 = np.array([1, 2, 3])
output_array = np.empty_like(array1)
hap = np.add(array1, array2, out=output_array)
print(hap)

[11 22 33]


3번 퀘스트

<aside>
👉 다음 배열에 대해 NumPy 유니버설 함수를 사용하여 요소별로 자연로그(log)를 계산하고, 특정 조건(`log 값 > 1`)을 만족하는 요소만 출력하는 코드를 작성하세요.

</aside>

In [23]:
array = np.array([1, np.e, 10, 100])
log_array = np.log(array)
print(log_array[log_array>1])

[2.30258509 4.60517019]
